# Generated by Django 5.2.3 on 2025-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('CHEF_PROJET', 'Chef de projet'), ('MEMBRE', 'Membre')], default='MEMBRE', max_length=20, verbose_name='Rôle du Membre'),
        ),
    ]
