# Generated by Django 5.2.3 on 2025-07-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_membre_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='projets_membre', to='api.membre'),
        ),
    ]
