# Generated by Django 5.2.3 on 2025-07-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projet_membres'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
