# Generated by Django 5.2.3 on 2025-07-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tache_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='chemin',
        ),
        migrations.AddField(
            model_name='fichier',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='fichiers/'),
        ),
    ]
