# Generated by Django 5.2.3 on 2025-07-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_fichier_chemin_fichier_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage"),
        ),
        migrations.AddField(
            model_name='membre',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Compte actif'),
        ),
    ]
